Repository weka/terraform-gcp-weka, pull requests merged in 2023-10, with the labels that each got.

#96 fix: add template metadata to scale up instance creation
  cloud-functions/functions/scale_up/scale_up.go
Labels: fix

#98 chore: remove nvme from clients and protocol gateways
  modules/clients/main.tf
  modules/protocol_gateways/main.tf
Labels: chore

#101 fix: change secrets replication to regional
  secret_manager.tf
Labels: fix

#100 feat: change bucket to uniform access
  main.tf
Labels: feature

#107 feat: emit custom weka events on autoscaling
  cloud-functions/go.mod
  cloud-functions/go.sum
Labels: feature

#110 fix: adjust MAX memory per container to 384GB
  variables.tf
Labels: fix
