Repository weka/terraform-gcp-weka, pull requests merged in 2024-07, with the labels that each got.

#213 feat: add tiering params for weka fs group create
  README.md
  cloud-functions/go.mod
  cloud-functions/go.sum
  cloud-functions/main.go
  cloud_functions.tf
  variables.tf
Labels: feature

#215 chore: add LICENSE
  LICENSE
Labels: chore

#210 feat: add backends gvnic support
  README.md
  main.tf
  variables.tf
Labels: feature

#216 fix: update release branch create old weka version discovery
  release/create_new_release_branch.sh
Labels: fix

#220 feat: support other base branch for new release branch
  release/create_new_release_branch.sh
Labels: feature
