Repository weka/terraform-gcp-weka, pull requests merged in 2024-09, with the labels that each got.

#247 chore: update release scripts
  release/calculate_next_tag.sh
  release/create_draft_release.sh
  release/create_new_release_branch.sh
Labels: chore

#249 fix: update smb cluster name limits
  modules/protocol_gateways/variables.tf
  variables.tf
Labels: fix

#250 fix: post cluster creation script
  cloud-functions/functions/clusterize/clusterize.go
Labels: fix

#253 feat: add gcp consumption labels
  cloud_functions.tf
  health_check.tf
  main.tf
  modules/clients/main.tf
  modules/network/main.tf
  modules/protocol_gateways/main.tf
  modules/shared_vpcs/main.tf
  modules/worker_pool/main.tf
  secret_manager.tf
  state_object.tf
  workflows.tf
Labels: feature

#254 fix: handle scale up instance fetching timeout
  cloud-functions/common/common.go
  cloud-functions/main.go
Labels: fix

#255 fix: filter out the header from s3 cluster status command
  modules/protocol_gateways/setup_s3.sh
Labels: fix
