Repository weka/terraform-gcp-weka, pull requests merged in 2024-04, with the labels that each got.

#174 chore: add project id to secrets
  secret_manager.tf
Labels: chore

#173 fix: remove yum update from init script
  cloud-functions/functions/scale_up/scale_up.go
Labels: fix

#175 feat: upgrade go runtime to 1.22
  cloud-functions/cloud_functions_test.go
  cloud-functions/go.mod
  cloud-functions/go.sum
  cloud_functions.tf
Labels: feature
