Repository weka/terraform-gcp-weka, pull requests merged in 2024-08, with the labels that each got.

#233 feat: handle redundant instances in clusterize
  cloud-functions/common/common.go
  cloud-functions/common/errors.go
  cloud-functions/functions/clusterize/clusterize.go
  cloud-functions/main.go
Labels: feature

#239 chore: add lb balancing mode
  health_check.tf
Labels: chore

#240 chore: update go-cloud-lib: report deployment user creation
  cloud-functions/go.mod
  cloud-functions/go.sum
Labels: chore

#243 fix: clients private repo
  modules/clients/init.sh
Labels: fix

#244 fix: use nfs object state for NFS get deploy script
  cloud-functions/functions/deploy/deploy.go
Labels: fix
