Repository weka/terraform-gcp-weka, pull requests merged in 2024-11, with the labels that each got.

#265 fix: first nic discovery
  cloud-functions/go.mod
  cloud-functions/go.sum
Labels: fix

#267 fix: get core ids for multiple numas
  cloud-functions/go.mod
  cloud-functions/go.sum
Labels: fix

#268 feat: add deletion_protection for workflows (gcp provider 6.11.0)
  workflows.tf
Labels: feature

#270 fix: remove bc package dependency
  cloud-functions/functions/clusterize/clusterize.go
Labels: fix

#271 fix: remove redundant quote in tiering percent calculation
  cloud-functions/functions/clusterize/clusterize.go
Labels: fix

#272 chore: increase nfs interface group timeout
  cloud-functions/go.mod
  cloud-functions/go.sum
Labels: chore
